# -*- coding: utf-8 -*-
"""Steam.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e2jkVefAnJlAqC-J2EGNGGDeHZHAf79i
"""

"""
=============================================================================
 PROJETO DE DATA SCIENCE — ANÁLISE E MACHINE LEARNING DE JOGOS DA STEAM
=============================================================================
Análise de milhares de jogos para responder a perguntas de negócio do mercado
indie/AAA e aplicar Machine Learning (Regressão, Classificação e Clusterização + PCA).

Como rodar:
  pip install pandas numpy scikit-learn xgboost lightgbm matplotlib seaborn
  python steam_analytics.py
=============================================================================
"""

import os
import warnings
from math import pi

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    roc_auc_score, roc_curve, confusion_matrix, mean_squared_error, r2_score
)

warnings.filterwarnings("ignore")

FIG_DIR = "steam_figures"
os.makedirs(FIG_DIR, exist_ok=True)

# =============================================================================
# ESTILO VISUAL GLOBAL (Tema Dark/Steam)
# =============================================================================
PALETTE = {"primary": "#66C0F4", "secondary": "#1B2838", "accent": "#C7D5E0", "highlight": "#2A475E"}
MODEL_COLORS = ["#5C6BC0", "#2EC4B6", "#FFB74D", "#E85D75"]
MODEL_ORDER = ["Logistic Regression", "Random Forest", "XGBoost", "LightGBM"]
COLOR_MAP = dict(zip(MODEL_ORDER, MODEL_COLORS))

plt.rcParams.update({
    "figure.facecolor": "#171A21", "axes.facecolor": "#1B2838",
    "axes.edgecolor": "#2A475E", "axes.grid": True,
    "grid.color": "#2A475E", "grid.linewidth": 0.6,
    "text.color": "#C7D5E0", "axes.labelcolor": "#C7D5E0",
    "xtick.color": "#C7D5E0", "ytick.color": "#C7D5E0",
    "axes.axisbelow": True, "font.size": 11,
    "axes.titlesize": 14, "axes.titleweight": "bold",
    "figure.dpi": 110, "savefig.dpi": 160, "savefig.bbox": "tight",
})


# =============================================================================
# 1. GERADOR / CARREGADOR DE DADOS DA STEAM (SINTÉTICO PARA EXECUÇÃO)
# =============================================================================
def load_steam_data(n_samples=5000):
    print(">> Sincronizando e Carregando catálogo de jogos da Steam...")
    np.random.seed(42)

    publishers = ["Valve", "Electronic Arts", "Ubisoft", "Devolver Digital",
                  "Indie Studio A", "Indie Studio B", "Square Enix", "Klei Entertainment"]
    genres_list = ["Action", "RPG", "Strategy", "Casual", "Indie", "Adventure", "Simulation"]

    data = {
        "game_id": range(1000, 1000 + n_samples),
        "price": np.random.choice([0, 9.99, 14.99, 19.99, 29.99, 59.99, 69.99], size=n_samples, p=[0.15, 0.2, 0.25, 0.15, 0.1, 0.1, 0.05]),
        "total_reviews": np.random.exponential(scale=1500, size=n_samples).astype(int) + 10,
        "is_indie": np.random.choice([1, 0], size=n_samples, p=[0.65, 0.35]),
        "publisher": np.random.choice(publishers, size=n_samples),
        "primary_genre": np.random.choice(genres_list, size=n_samples),
        "days_since_release": np.random.randint(30, 3650, size=n_samples)
    }

    df = pd.DataFrame(data)

    # Gerando regras de negócio realistas para avaliações
    # Jogos indies e jogos com preço razoável tendem a ter avaliações ligeiramente mais altas
    base_rating = 0.70 + (df["is_indie"] * 0.08) - (df["price"] / 500) + np.random.normal(0, 0.1, n_samples)
    df["positive_ratio"] = np.clip(base_rating, 0.1, 0.99)
    df["positive_reviews"] = (df["total_reviews"] * df["positive_ratio"]).astype(int)
    df["high_rating"] = (df["positive_ratio"] >= 0.80).astype(int) # Alvo de classificação

    print(f"   Dataset carregado: {df.shape[0]} jogos e {df.shape[1]} atributos.")
    return df


# =============================================================================
# 2. TRATAMENTO E FEATURE ENGINEERING
# =============================================================================
def clean_and_transform(df):
    print(">> Tratando dados e criando novas features de jogos...")

    # Tratando nulos se existirem
    df = df.dropna().copy()

    # Novas Features
    df["is_free"] = (df["price"] == 0).astype(int)
    df["log_reviews"] = np.log1p(df["total_reviews"]) # Suavização logarítmica para reviews
    df["estimated_revenue"] = df["price"] * df["total_reviews"] # Sucesso Comercial estimado
    df["commercial_success"] = (df["estimated_revenue"] > df["estimated_revenue"].median()).astype(int)

    return df


# =============================================================================
# 3. ANÁLISE EXPLORATÓRIA (RESPONDENDO ÀS 5 PERGUNTAS)
# =============================================================================
def run_steam_eda(df):
    print(">> Executando Análise Exploratória e gerando respostas de negócio...")

    # P1: Quais gêneros possuem as melhores avaliações?
    fig, ax = plt.subplots(figsize=(8, 4.5))
    genre_ratings = df.groupby("primary_genre")["positive_ratio"].mean().sort_values(ascending=False) * 100
    sns.barplot(x=genre_ratings.values, y=genre_ratings.index, palette="mako", ax=ax)
    ax.set_title("1. Avaliação Média (% Positiva) por Gênero", color="white")
    ax.set_xlabel("% Média de Avaliações Positivas")
    plt.tight_layout()
    plt.savefig(f"{FIG_DIR}/01_generos_avaliacoes.png")
    plt.close()

    # P2: Jogos Indie são mais bem avaliados?
    fig, ax = plt.subplots(figsize=(6, 4.5))
    sns.boxplot(data=df, x="is_indie", y="positive_ratio", palette=["#E85D75", "#2EC4B6"], ax=ax)
    ax.set_xticklabels(["AAA / Grandes Estúdios", "Indie"])
    ax.set_title("2. Distribuição de Avaliações: Indie vs AAA", color="white")
    ax.set_ylabel("Proporção de Avaliações Positivas")
    plt.tight_layout()
    plt.savefig(f"{FIG_DIR}/02_indie_vs_aaa.png")
    plt.close()

    # P3: Existe relação entre preço e nota?
    fig, ax = plt.subplots(figsize=(7, 5))
    sns.scatterplot(data=df, x="price", y="positive_ratio", alpha=0.4, color=PALETTE["primary"], ax=ax)
    sns.regplot(data=df, x="price", y="positive_ratio", scatter=False, color="#E85D75", ax=ax)
    ax.set_title("3. Relação Preço vs. Avaliação Positiva", color="white")
    ax.set_xlabel("Preço ($)")
    ax.set_ylabel("Proporção Positiva")
    plt.tight_layout()
    plt.savefig(f"{FIG_DIR}/03_preco_vs_nota.png")
    plt.close()

    # P4: Jogos gratuitos recebem mais reviews?
    fig, ax = plt.subplots(figsize=(6, 4.5))
    sns.barplot(data=df, x="is_free", y="total_reviews", palette=["#FFB74D", "#5C6BC0"], ax=ax)
    ax.set_xticklabels(["Pagos", "Gratuitos (Free-to-Play)"])
    ax.set_title("4. Média de Reviews: Jogos Pagos vs Gratuitos", color="white")
    ax.set_ylabel("Média de Avaliações Recebidas")
    plt.tight_layout()
    plt.savefig(f"{FIG_DIR}/04_gratuitos_vs_reviews.png")
    plt.close()

    # P5: Quais publishers lançam os jogos mais bem avaliados?
    fig, ax = plt.subplots(figsize=(9, 4.5))
    pub_ratings = df.groupby("publisher")["positive_ratio"].mean().sort_values(ascending=True) * 100
    ax.barh(pub_ratings.index, pub_ratings.values, color="#2EC4B6")
    ax.set_title("5. Top Publishers por Nota Média", color="white")
    ax.set_xlabel("% Média Positiva")
    plt.tight_layout()
    plt.savefig(f"{FIG_DIR}/05_top_publishers.png")
    plt.close()


# =============================================================================
# 4. CLUSTERIZAÇÃO E PCA (DESCOBERTA DE PERFIS DE JOGOS)
# =============================================================================
def run_clusterization_pca(df):
    print(">> Executando Clusterização (K-Means) e Redução de Dimensionalidade (PCA)...")
    features_cluster = ["price", "log_reviews", "positive_ratio", "days_since_release"]

    X_clust = df[features_cluster]
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X_clust)

    # K-Means
    kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
    df["cluster"] = kmeans.fit_predict(X_scaled)

    # PCA para projeção 2D
    pca = PCA(n_components=2)
    pca_coords = pca.fit_transform(X_scaled)
    df["pca_1"] = pca_coords[:, 0]
    df["pca_2"] = pca_coords[:, 1]

    fig, ax = plt.subplots(figsize=(8, 6))
    sns.scatterplot(data=df, x="pca_1", y="pca_2", hue="cluster", palette="viridis", alpha=0.7, ax=ax)
    ax.set_title("Agrupamento de Jogos na Steam (Clusterização K-Means + PCA 2D)", color="white")
    ax.set_xlabel("Componente Principal 1")
    ax.set_ylabel("Componente Principal 2")
    plt.tight_layout()
    plt.savefig(f"{FIG_DIR}/06_clusters_steam_pca.png")
    plt.close()


# =============================================================================
# 5. MACHINE LEARNING: PREDIÇÃO DE AVALIAÇÃO POSITIVA (CLASSIFICAÇÃO)
# =============================================================================
def train_classification_models(df):
    print(">> Preparando Machine Learning (Classificação de Sucesso/Rating)...")

    # Encoding de Categóricas
    df_encoded = pd.get_dummies(df, columns=["primary_genre", "publisher"], drop_first=True)

    features = [c for c in df_encoded.columns if c not in ["game_id", "high_rating", "positive_ratio", "positive_reviews", "estimated_revenue", "commercial_success"]]
    X = df_encoded[features]
    y = df_encoded["high_rating"]

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

    scaler = StandardScaler()
    X_train_s = scaler.fit_transform(X_train)
    X_test_s = scaler.transform(X_test)

    models = {
        "Logistic Regression": LogisticRegression(random_state=42),
        "Random Forest": RandomForestClassifier(n_estimators=200, random_state=42),
        "XGBoost": XGBClassifier(n_estimators=150, eval_metric="logloss", random_state=42),
        "LightGBM": LGBMClassifier(n_estimators=150, verbose=-1, random_state=42)
    }

    results = {}
    for name, model in models.items():
        model.fit(X_train_s, y_train)
        preds = model.predict(X_test_s)
        probas = model.predict_proba(X_test_s)[:, 1]

        results[name] = {
            "Accuracy": accuracy_score(y_test, preds),
            "Precision": precision_score(y_test, preds),
            "Recall": recall_score(y_test, preds),
            "F1-Score": f1_score(y_test, preds),
            "ROC-AUC": roc_auc_score(y_test, probas)
        }

    metrics_df = pd.DataFrame(results).T
    print("\n===== DESEMPENHO DOS MODELOS DE CLASSIFICAÇÃO =====")
    print(metrics_df.round(4))

    return metrics_df


# =============================================================================
# EXECUÇÃO PRINCIPAL
# =============================================================================
if __name__ == "__main__":
    df = load_steam_data(n_samples=5000)
    df = clean_and_transform(df)

    run_steam_eda(df)
    run_clusterization_pca(df)
    metrics_df = train_classification_models(df)

    print(f"\nProjeto concluído! Todas as visualizações foram salvas em '{FIG_DIR}/'.")

"""
=============================================================================
 PROJETO DE DATA SCIENCE — STEAM: SÉRIES TEMPORAIS E DINÂMICA DE MERCADO
=============================================================================
Análise temporal de picos de jogadores (CCU), efeito de promoções,
elasticidade-preço da demanda e previsão com aprendizado supervisionado.

Como rodar:
  pip install pandas numpy scikit-learn matplotlib seaborn
  python steam_time_series.py
=============================================================================
"""

import os
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_percentage_error, r2_score
from sklearn.preprocessing import StandardScaler

warnings.filterwarnings("ignore")

FIG_DIR = "steam_figures_timeseries"
os.makedirs(FIG_DIR, exist_ok=True)

# Configuração visual global (Steam Dark Theme)
plt.rcParams.update({
    "figure.facecolor": "#171A21", "axes.facecolor": "#1B2838",
    "axes.edgecolor": "#2A475E", "axes.grid": True,
    "grid.color": "#2A475E", "grid.linewidth": 0.6,
    "text.color": "#C7D5E0", "axes.labelcolor": "#C7D5E0",
    "xtick.color": "#C7D5E0", "ytick.color": "#C7D5E0",
    "axes.axisbelow": True, "font.size": 11,
    "axes.titlesize": 13, "axes.titleweight": "bold",
    "figure.dpi": 110, "savefig.dpi": 160, "savefig.bbox": "tight"
})


# =============================================================================
# 1. GERADOR DE SÉRIE TEMPORAL SINTÉTICA DE JOGOS DA STEAM
# =============================================================================
def generate_steam_timeseries(days=730):
    """
    Gera uma série diária de 2 anos simulando métricas de um jogo na Steam.
    Inclui tendência, sazonalidade de fim de semana, promoções e ruído.
    """
    print(">> Gerando série temporal histórica de métricas da Steam...")
    np.random.seed(42)
    dates = pd.date_range(start="2024-01-01", periods=days, freq="D")

    # 1. Componentes da Série
    base_ccu = 15000
    decay_trend = np.exp(-np.linspace(0, 2.5, days)) * 30000  # Queda natural pós-lançamento
    steady_trend = 5000

    # Sazonalidade semanal (Picos no fim de semana)
    day_of_week = dates.dayofweek
    weekend_seasonality = np.where(day_of_week >= 5, 1.4, 1.0)

    # Promoções (Steam Summer Sale, Winter Sale, Discounts aleatórios)
    is_sale_event = np.zeros(days)
    # Summer sale (Julho) e Winter Sale (Dezembro)
    for i, date in enumerate(dates):
        if (date.month == 7 and 10 <= date.day <= 24) or (date.month == 12 and 18 <= date.day <= 31):
            is_sale_event[i] = 1
        elif np.random.rand() < 0.03: # Desconto pontual de distribuidora
            is_sale_event[i] = 1

    # Desconto aplicado (%)
    discount_pct = np.where(is_sale_event == 1, np.random.choice([0.20, 0.33, 0.50, 0.75], size=days), 0.0)
    base_price = 49.99
    effective_price = base_price * (1 - discount_pct)

    # Elasticidade da demanda: Descontos geram picos em CCU e vendas
    price_boost = 1.0 + (discount_pct * 2.8)

    # CCU Final (Peak Concurrent Users)
    noise = np.random.normal(1.0, 0.08, size=days)
    ccu = (base_ccu + decay_trend + steady_trend) * weekend_seasonality * price_boost * noise

    # Unidades vendidas estimadas (proporcional ao CCU)
    daily_sales = (ccu * np.random.uniform(0.05, 0.12, size=days) * price_boost).astype(int)

    df = pd.DataFrame({
        "date": dates,
        "ccu": ccu.astype(int),
        "daily_sales": daily_sales,
        "base_price": base_price,
        "discount_pct": discount_pct,
        "effective_price": effective_price,
        "is_sale_event": is_sale_event.astype(int),
        "day_of_week": day_of_week,
        "month": dates.month
    }).set_index("date")

    return df


# =============================================================================
# 2. ANÁLISE DE ELASTICIDADE-PREÇO DA DEMANDA (E_d)
# =============================================================================
def analyze_price_elasticity(df):
    """
    Calcula a Elasticidade-Preço da Demanda (E_d) durante dias de promoção.
    E_d = (% variação na quantidade vendida) / (% variação no preço)
    """
    print(">> Calculando a Elasticidade-Preço da Demanda (Price Elasticity of Demand)...")

    baseline_sales = df[df["discount_pct"] == 0]["daily_sales"].mean()
    baseline_price = df["base_price"].iloc[0]

    discount_levels = [0.20, 0.33, 0.50, 0.75]
    elasticity_data = []

    for disc in discount_levels:
        sales_at_disc = df[df["discount_pct"] == disc]["daily_sales"].mean()
        p_eff = baseline_price * (1 - disc)

        pct_change_q = (sales_at_disc - baseline_sales) / baseline_sales
        pct_change_p = (p_eff - baseline_price) / baseline_price

        # Fórmula da Elasticidade
        e_d = pct_change_q / pct_change_p

        elasticity_data.append({
            "Desconto (%)": f"{int(disc*100)}%",
            "Preço Promocional ($)": f"{p_eff:.2f}",
            "Vendas Diárias Médias": int(sales_at_disc),
            "Variacão Qtd (%)": f"{pct_change_q * 100:+.1f}%",
            "Elasticidade (E_d)": round(e_d, 2)
        })

    elasticity_df = pd.DataFrame(elasticity_data)
    print("\n===== TABELA DE ELASTICIDADE-PREÇO DA DEMANDA =====")
    print(elasticity_df.to_string(index=False))

    # Gráfico de Elasticidade
    fig, ax = plt.subplots(figsize=(7, 4.5))
    discs = [d * 100 for d in discount_levels]
    e_vals = [abs(float(row["Elasticidade (E_d)"])) for row in elasticity_data]

    ax.plot(discs, e_vals, marker="o", color="#66C0F4", linewidth=2.5, markersize=8)
    ax.axhline(1.0, linestyle="--", color="#E85D75", label="E_d = 1.0 (Demanda Neutra)")
    ax.set_title("Elasticidade-Preço da Demanda por Faixa de Desconto", color="white")
    ax.set_xlabel("Percentual de Desconto na Steam (%)")
    ax.set_ylabel("Elasticidade |E_d| (Módulo)")
    ax.legend()
    plt.tight_layout()
    plt.savefig(f"{FIG_DIR}/01_elasticidade_preco.png")
    plt.close()


# =============================================================================
# 3. CURVA DE RETENÇÃO / DECAIMENTO DE JOGADORES (SOBREVIVÊNCIA)
# =============================================================================
def plot_retention_decay(df):
    """
    Analisa a taxa de retenção natural da base de jogadores ao longo do tempo.
    """
    print(">> Mapeando Curva de Retenção e Decaimento da Base Ativa...")

    # Filtrar os primeiros 365 dias para observar a retenção pós-lançamento sem ruído de promoções
    first_year = df.iloc[:365].copy()
    peak_ccu = first_year["ccu"].max()
    retention_pct = (first_year["ccu"] / peak_ccu) * 100

    fig, ax = plt.subplots(figsize=(8, 4.5))
    ax.plot(range(len(retention_pct)), retention_pct, color="#2EC4B6", linewidth=1.8)

    # Destacar marcos de retenção (D1, D30, D90, D365)
    checkpoints = [1, 30, 90, 365]
    for cp in checkpoints:
        if cp < len(retention_pct):
            val = retention_pct.iloc[cp]
            ax.scatter(cp, val, color="#FFB74D", s=50, zorder=5)
            ax.annotate(f"D{cp}: {val:.1f}%", (cp, val), textcoords="offset points",
                        xytext=(10, 5), color="white", fontweight="bold")

    ax.set_title("Curva de Decaimento de Jogadores Ativos (Retenção Pós-Lançamento)", color="white")
    ax.set_xlabel("Dias Pós-Lançamento")
    ax.set_ylabel("% em Relação ao Pico do Lançamento")
    plt.tight_layout()
    plt.savefig(f"{FIG_DIR}/02_curva_retencao_jogadores.png")
    plt.close()


# =============================================================================
# 4. FEATURE ENGINEERING PARA SÉRIES TEMPORAIS (LAGS & ROLLING)
# =============================================================================
def create_timeseries_features(df):
    """
    Cria variáveis defasadas (Lags), médias móveis e atributos calendários.
    """
    print(">> Criando Lags, Médias Móveis e Atributos Calendários para Machine Learning...")
    df_feat = df.copy()

    # Lag Features (Valores passados)
    for lag in [1, 2, 7, 14]:
        df_feat[f"ccu_lag_{lag}"] = df_feat["ccu"].shift(lag)

    # Rolling Features (Médias e Desvios móveis)
    df_feat["ccu_rolling_7_mean"] = df_feat["ccu"].shift(1).rolling(window=7).mean()
    df_feat["ccu_rolling_30_mean"] = df_feat["ccu"].shift(1).rolling(window=30).mean()
    df_feat["ccu_rolling_7_std"] = df_feat["ccu"].shift(1).rolling(window=7).std()

    # Atributos Cíclicos do Calendário
    df_feat["is_weekend"] = np.where(df_feat["day_of_week"] >= 5, 1, 0)

    df_feat = df_feat.dropna()
    return df_feat


# =============================================================================
# 5. MODELAGEM PREDITIVA E FORECASTING DE CCU
# =============================================================================
def train_ccu_forecasting_model(df):
    """
    Treina um modelo de Machine Learning para prever o pico diário de jogadores (CCU).
    A divisão é temporal (Train nos primeiros 80% do tempo, Test nos últimos 20%).
    """
    print(">> Treinando modelo de Forecasting de Jogadores Simultâneos (Random Forest)...")

    df_feat = create_timeseries_features(df)

    features = [c for c in df_feat.columns if c not in ["ccu", "daily_sales"]]
    target = "ccu"

    # Split Temporal (Sem Shuffle)
    split_idx = int(len(df_feat) * 0.8)
    train = df_feat.iloc[:split_idx]
    test = df_feat.iloc[split_idx:]

    X_train, y_train = train[features], train[target]
    X_test, y_test = test[features], test[target]

    # Modelagem
    model = RandomForestRegressor(n_estimators=200, max_depth=10, random_state=42)
    model.fit(X_train, y_train)

    preds = model.predict(X_test)

    # Avaliação do Modelo
    rmse = np.sqrt(mean_squared_error(y_test, preds))
    mape = mean_absolute_percentage_error(y_test, preds) * 100
    r2 = r2_score(y_test, preds)

    print("\n===== DESEMPENHO DO MODELO DE FORECASTING (TESTE) =====")
    print(f"  RMSE (Erro Quadrático Médio): {rmse:.2f} jogadores")
    print(f"  MAPE (Erro Percentual Médio): {mape:.2f}%")
    print(f"  R² Score (Variância Explicada): {r2:.4f}")

    # Visualização: Real vs Predito
    fig, ax = plt.subplots(figsize=(10, 5))
    ax.plot(test.index, y_test.values, label="CCU Real", color="#66C0F4", linewidth=1.8)
    ax.plot(test.index, preds, label="CCU Predito (ML)", color="#FFB74D", linestyle="--", linewidth=1.8)

    # Destaque para eventos de promoção no conjunto de teste
    sales_in_test = test[test["is_sale_event"] == 1]
    if not sales_in_test.empty:
        ax.scatter(sales_in_test.index, sales_in_test["ccu"], color="#E85D75",
                   label="Steam Sale Event", zorder=5, s=35)

    ax.set_title("Previsão de Jogadores Simultâneos (CCU Forecast)", color="white")
    ax.set_xlabel("Data")
    ax.set_ylabel("Pico de Jogadores (CCU)")
    ax.legend(loc="upper right")
    plt.tight_layout()
    plt.savefig(f"{FIG_DIR}/03_previsao_ccu_timeseries.png")
    plt.close()


# =============================================================================
# MAIN
# =============================================================================
if __name__ == "__main__":
    df_ts = generate_steam_timeseries(days=730)

    analyze_price_elasticity(df_ts)
    plot_retention_decay(df_ts)
    train_ccu_forecasting_model(df_ts)

    print(f"\n Módulo de Séries Temporais concluído! Gráficos salvos em '{FIG_DIR}/'.")